### ISSUE TITLE
Basic examples don't build

### ISSUE THREAD

**Issue by gokhansa** [corda/samples-kotlin#19]
The last merge commit that updates config of the (Merge pull request #18 from corda/NOTICK-update-artifactory-hostnames : https://github.com/corda/samples-kotlin/commit/3d28bb27de8eedd7dd39eff3bb0c0b48d8ea2193) breaks samples-kotlin/Basic apps (tried yo-cordapp and cordapp-example) compiles. As Following errors printed: 

`A problem occurred configuring root project 'cordapp-example'.
> Could not resolve all artifacts for configuration ':classpath'.
> Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71.
Searched in the following locations:
- file:/C:/Users/username/.m2/repository/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.pom
- file:/C:/Users/username/.m2/repository/org/jetbrains/kotlin/kotlin-gradle-plugin/1.2.71/kotlin-gradle-plugin-1.2.71.jar
Required by:
project :
> Could not find net.corda.plugins:cordapp:5.0.12.
Searched in the following locations:
- file:/C:/Users/username/.m2/repository/net/corda/plugins/cordapp/5.0.12/cordapp-5.0.12.pom
- file:/C:/Users/username/.m2/repository/net/corda/plugins/cordapp/5.0.12/cordapp-5.0.12.jar
Required by:
project :
> Could not find net.corda.plugins:cordformation:5.0.12.
Searched in the following locations:
- file:/C:/Users/username/.m2/repository/net/corda/plugins/cordformation/5.0.12/cordformation-5.0.12.pom
- file:/C:/Users/username/.m2/repository/net/corda/plugins/cordformation/5.0.12/cordformation-5.0.12.jar
Required by:
project :
> Could not find net.corda.plugins:quasar-utils:5.0.12.
Searched in the following locations:
- file:/C:/Users/username/.m2/repository/net/corda/plugins/quasar-utils/5.0.12/quasar-utils-5.0.12.pom
- file:/C:/Users/username/.m2/repository/net/corda/plugins/quasar-utils/5.0.12/quasar-utils-5.0.12.jar
Required by:
project :

Possible solution:
- Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

The *temporary solution* that makes the projects compile: undoing the changes:
1) Basic/constant.properties, update the first line to old version:
cordaReleaseGroup=net.corda

2) For cordapp-example, in gradle.build repositories undo comments: 
repositories {
        mavenCentral()
        jcenter()
        maven {
            url 'https://ci-artifactory.corda.r3cev.com/artifactory/corda-releases'
        }
        mavenLocal()
}

**Comment by anixon604** [comment]
Thanks for catching this @gokhansa, the fix has been applied via bd2b5. cheers.
